config/routes.rb
Rails.application.routes.draw do
  
  resources :messages, only: [:new, :create]

  resources :charges, only: [:new, :create, :index]
  get '/payments', to: 'charges#payments'
  
  resources :banks, only: [:new, :create, :index]

  root 'welcome#index'
  
  get '/home', to: 'welcome#home'
  
  get '/support', to: 'support#index'
  get '/support/files', to: 'support#files'
  
  resources :orders, only: [:new, :create]
  
  resources :readings
  resources :users, except: [:destroy]
  
  get '/users/:id/readings' => 'users#readings', :as => :user_readings
  
  get '/readings/:id/record' => 'readings#record', :as => 'record_reading'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

end

app/models/user.rb
class User < ActiveRecord::Base
   
    before_save { self.company = company.upcase }
    has_many :readings
    has_many :charges
    has_many :banks
    validates :customer_number, presence: true, uniqueness: { case_sensitive: false }
    validates :company, presence: true
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
   
   before_action :set_user, only: [:edit, :update, :show]
   #before_action :require_same_user, only: []
   before_action :require_admin, except: [:show]

   
   def index
      @users = User.all.order('customer_number ASC').paginate(page: params[:page], per_page: 20)
   end
   
   def show
      @readings = @user.readings.order('updated_at DESC').paginate(page: params[:page], per_page: 10)
      @charges = @user.charges.order('created_at DESC')
      @banks = @user.banks.order('created_at DESC')
   end

   def new 
      @user = User.new
   end
   
   def create
      @user = User.new(user_params)
      
      if @user.save
         flash[:success] = "Customer has been added."
         redirect_to users_path
      else
         render 'new'
      end
   end
   
   def edit
      
   end
   
   def update
      if @user.update(user_params)
          flash[:success] = "Customer has been updated."
          redirect_to user_path(@user)
      else
         render 'edit'
      end
   end

   private
   
   def user_params
      params.require(:user).permit(:customer_number, :company, :password)
   end

   def set_user
    @user = User.find(params[:id])
   end

   def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only view and edit your own profile"
      redirect_to root_path
    end
   end

end

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
    <div class="col-md-6 well col-md-offset-3">
        <h4>Please reference your invoice for your Customer Number.</h4>
        <%= form_for @user do |f| %>
            <%= f.label :company, "Company:" %>
            <%= f.text_field :company %>
            
            <%= f.label :customer_number, "Customer Number:" %>
            <%= f.text_field :customer_number %>
            
            <%= f.label :password, "Password:" %>
            <%= f.password_field :password %>
            
            <%= f.submit (@user.new_record? ? 'Add Customer' : 'Edit Customer'), class: "btn btn-success" %>
        <% end %>
            
    </div>
</div>

app/views/users/edit.html.erb
<%= render 'shared/page_title', title: "Edit Customer" %>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="container">
<h1>All Customers</h1>
<hr/>
<div class="center">
<%= link_to "Add Customers", new_user_path, class: "center btn btn-success btn-white-text" %>
<br><br>
<%= will_paginate %>
</div>
<% @users.each do |user| %>
    <div class="col-md-8 col-md-offset-2 row well">
        <div class="col-md-2">
            <h4><%= link_to user.customer_number, user_path(user) %></h4>
        </div>
        <div class="col-md-10">
            <h4><%= user.company %></h4>
        </div>
    </div>
<% end %>
<div class="center">
<%= will_paginate %>
</div>
</div>

app/views/users/new.html.erb
<%= render 'shared/page_title', title: "Add Customer" %>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="container">
<h1>Readings and Payments for Customer Number: <%= @user.customer_number %></h1>
<h4 class="center"><%= @user.company %></h4>
<hr/>
<% if logged_in? && current_user.admin? == true %>
<div class="center">
<%= link_to "Edit Customer", edit_user_path(@user), class: "center btn btn-success btn-white-text" %><br>

</div>
<% end %>
<br>

    <div class="row well">
        <div class="col-md-12">
            <% @readings.each do |reading| %>
              <p class="center">Equipment ID Number: <%= link_to reading.equipment_number, reading_path(reading) %> - <span class="quiet"><small><%= time_ago_in_words(reading.created_at) %> ago</small></span></p> 

            <% end %>
        </div>
    </div>
    <div class="row well">
        <h2>Card Payments</h2>
        <% @charges.each do |charge| %>
        <div class="col-sm-3 invoice-list">
              <p>Invoice Number: <%= charge.invoice %></p> 
        </div>
        <div class="col-sm-3 invoice-list">
              <p>Payment Amount: $<%= charge.amount %></p>  
        </div>
        <div class="col-sm-3 invoice-list">
              <p>Paid By: <%= charge.customer %></p> 
        </div>
        <div class="col-sm-3 invoice-list">
              <span class="quiet"><small><%= time_ago_in_words(charge.created_at) %> ago</small></span> 
        </div>
        <% end %>
    </div>
    <div class="row well">
        <h2>Bank Payments</h2>
        <% @banks.each do |bank| %>
        <div class="col-sm-3 invoice-list">
              <p>Invoice Number: <%= bank.invoice %></p> 
        </div>
        <div class="col-sm-3 invoice-list">
              <p>Payment Amount: $<%= bank.amount %></p>  
        </div>
        <div class="col-sm-3 invoice-list">
              <p>Paid By: <%= bank.customer %></p> 
        </div>
        <div class="col-sm-3 invoice-list">
              <span class="quiet"><small><%= time_ago_in_words(bank.created_at) %> ago</small></span> 
        </div>
        <% end %>
    </div>
    
    
</div>
</div>