config/routes.rb
Rails.application.routes.draw do
  
  resources :messages, only: [:new, :create]

  resources :charges, only: [:new, :create, :index]
  get '/payments', to: 'charges#payments'
  
  resources :banks, only: [:new, :create, :index]

  root 'welcome#index'
  
  get '/home', to: 'welcome#home'
  
  get '/support', to: 'support#index'
  get '/support/files', to: 'support#files'
  
  resources :orders, only: [:new, :create]
  
  resources :readings
  resources :users, except: [:destroy]
  
  get '/users/:id/readings' => 'users#readings', :as => :user_readings
  
  get '/readings/:id/record' => 'readings#record', :as => 'record_reading'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_action :require_user, only: [:home]

  def index
  
  end
  
  def home
    
  end
  

end

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <div class="container">
    <h1>Welcome to the QBS<br>Customer Page</h1>
    
    <%= link_to "Submit Meter Readings", new_reading_path, class: "btn btn-lg btn-primary btn-white-text btn-support" %>
    <%= link_to "Make Payment", payments_path, class: "btn btn-lg btn-success btn-white-text btn-support" %>
    <%= link_to "Support and Supplies", support_path, class: "btn btn-lg btn-danger btn-white-text btn-support" %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron">
  <div class="container">
    <h1>Welcome to the QBS<br>Customer Page</h1>
    <h2>Pay your bill, submit meter readings, access support, and order supplies.</h2>
    
    <%= link_to "Access Your Account", login_path, class: "btn btn-lg btn-success btn-white-text" %>
    
    <h3>Don't have an account yet? Can't remember your password? Contact us at <a href="tel://1-410-337-3700">410-337-3700</a> or <a href="mailto:websites@copyquality.com?Subject=Login%20Account%20Help" target="_top">websites@copyquality.com</a> for account support.</h3>
  </div>
</div>