config/routes.rb
Rails.application.routes.draw do
  
  resources :messages, only: [:new, :create]

  resources :charges, only: [:new, :create, :index]
  get '/payments', to: 'charges#payments'
  
  resources :banks, only: [:new, :create, :index]

  root 'welcome#index'
  
  get '/home', to: 'welcome#home'
  
  get '/support', to: 'support#index'
  get '/support/files', to: 'support#files'
  
  resources :orders, only: [:new, :create]
  
  resources :readings
  resources :users, except: [:destroy]
  
  get '/users/:id/readings' => 'users#readings', :as => :user_readings
  
  get '/readings/:id/record' => 'readings#record', :as => 'record_reading'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

end

app/controllers/support_controller.rb
class SupportController < ApplicationController
    
  before_action :require_user

  def index
  
  end
    
  def files
    
  end
 
  
end

app/views/support/index.html.erb
<div class="container support center">
  <h1>Support</h1>
  <hr/>
  <%= link_to "Drivers and Manuals", support_files_path, class: "btn btn-lg btn-primary btn-white-text btn-support" %>
  <%= link_to "Order Supplies", new_order_path, class: "btn btn-lg btn-success btn-white-text btn-support" %>
  <%= link_to "Request Support", new_message_path, class: "btn btn-lg btn-warning btn-white-text btn-support" %>
  <div class="visible-xs-block">
    <%= link_to "Call Support Now", "tel://1-410-337-3700", class: "btn btn-lg btn-danger btn-white-text btn-support" %>
  </div>
</div>