config/routes.rb
Rails.application.routes.draw do
  
  resources :messages, only: [:new, :create]

  resources :charges, only: [:new, :create, :index]
  get '/payments', to: 'charges#payments'
  
  resources :banks, only: [:new, :create, :index]

  root 'welcome#index'
  
  get '/home', to: 'welcome#home'
  
  get '/support', to: 'support#index'
  get '/support/files', to: 'support#files'
  
  resources :orders, only: [:new, :create]
  
  resources :readings
  resources :users, except: [:destroy]
  
  get '/users/:id/readings' => 'users#readings', :as => :user_readings
  
  get '/readings/:id/record' => 'readings#record', :as => 'record_reading'
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

end

app/views/layouts/_footer.html.erb
<footer>
	<div class="main-container sitemap">

		<div class="row">
			<div class="col-md-5">
			  
				<a href="https://twitter.com/qbs_copiers" target="_blank"><img src="http://copyquality.com/img/twitter.png" width="42" height="42" alt="Twitter" title="Twitter" border="0" /></a>

				<a href="https://www.facebook.com/QBSCopiers" target="_blank"><img src="http://copyquality.com/img/facebook.png" width="42" height="42" alt="Facebook" title="Facebook" border="0" /></a>

				<a href="https://www.linkedin.com/company/quality-business-solutions" target="_blank"><img src="http://copyquality.com/img/linkedin.png" width="42" height="42" alt="LinkedIn" title="LinkedIn" border="0" /></a>
				
				<a href="https://plus.google.com/106490611484951200602/about" target="_blank"><img src="http://copyquality.com/img/googleplus.png" width="42" height="42" alt="Google Plus" title="GooglePlus" border="0" /></a>

				<a href="https://www.youtube.com/user/baltimorecopiers" target="_blank"><img src="http://copyquality.com/img/youtube.png" width="42" height="42" alt="YouTube" title="YouTube" border="0" /></a><br><br>
			  
			  <a href="http://copyquality.com/privacypolicy.html" target="_blank">Privacy Policy</a><br>
			</div>
			<div class="col-md-5" align="center">
					<img src="http://copyquality.com/img/2016-Elite-Dealer.jpg" class="elite" alt="Elite Dealer 2016 Award" width="100px">
					<img src="http://copyquality.com/img/ssplogo.jpg" title="A Copystar Service Solution Provider (SSP) Dealer employs a highly certified service staff and represents Copystar's highest level of technical and solutions expertise." alt="Service Solution Provider Dealer" class="elite" width="100px">
		
				<div class="xr_noreset " style="width: 184px; height: 87px;" align="center">
					<a id="bbblink" class="rbhzbul" href="http://www.bbb.org/greater-maryland/business-reviews/office-equipment-leasing-and-repair-service/quality-business-solutions-in-baltimore-md-90170739#bbbseal" title="Quality Business Solutions, Office Equipment Leasing & Repair Service, Baltimore, MD" style="display: block;position: relative;overflow: hidden; width: 200px; height: 76px; margin: 0px; padding: 0px;">
					  <img style="padding: 0px; border: none;" id="bbblinkimg" src="http://seal-greatermd.bbb.org/logo/rbhzbul/quality-business-solutions-90170739.png" width="400" height="76" alt="Quality Business Solutions, Office Equipment Leasing & Repair Service, Baltimore, MD" /></a>
					  <script type="text/javascript">var bbbprotocol = ( ("https:" == document.location.protocol) ? "https://" : "http://" ); document.write(unescape("%3Cscript src='" + bbbprotocol + 'seal-greatermd.bbb.org' + unescape('%2Flogo%2Fquality-business-solutions-90170739.js') + "' type='text/javascript'%3E%3C/script%3E"));</script>
				</div>
			</div>
			
			<div class="col-md-2">
				<p class="footer-address"><strong>Quality Business Solutions</strong><br>&copy; 2016</p>
				<p class="footer-address"><strong>Physical Address:</strong><br>9525 Harford Road<br>Baltimore, MD 21234<br><br>
						<strong>Mailing Address:</strong><br>PO BOX 42668<br>Towson, MD 21284<br><br>
						<strong>Contact Us:</strong><br>
					<a href="mailto:info@copyquality.com?Subject=Hello%20QBS" target="_top">info@copyquality.com</a><br><a href="tel://1-410-337-3700">410-337-3700</a></p>
			</div><!-- end col -->
		</div><!-- end row -->
	</div><!-- container -->
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>">
                <%= message %>
                <a class="close" data-dismiss="alert">&#215;</a>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top main-nav navbar-right">
	<div class="container-fluid">
		<div class="row">
			
			<div class="col-sm-3">      
				<a class="navbar-brand" href="http://copyquality.com"><%= image_tag("qbs-logo180.png", :alt => "quality business solutions logo") %></a>
			</div>
			
			<div class="col-sm-9">
				<div class="navbar-header">
					<button type="button" class="btn btn-navbar navbar-toggle collapsed collapse.in" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Meter Readings", readings_path %></li>
        <li><%= link_to "Make Payment", payments_path %></li>
        <li><%= link_to "Support", support_path %></li>
        <% end %>
        <% if logged_in? && current_user.admin? == false %>
        <li><%= link_to "History", user_path(current_user) %></li>
        <% end %>
        <% if logged_in? && current_user.admin? == true %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Customers", users_path %></li>
            <li><%= link_to "All Readings", readings_path %></li>
            <li><%= link_to "All Bank Payments", banks_path %></li>
            <li><%= link_to "All Card Payments", charges_path %></li>
            <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
          </ul>
        </li>
        <% end %>
        <% if !logged_in? %>
        <li><%= link_to "Login", login_path %></li>
        <% else %>
        <li><%= link_to "Logout", logout_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quality Business Solutions - Customer Portal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="http://copyquality.com/favicon.ico" type="image/x-icon" />
  <link rel="shortcut icon" href="http://copyquality.com/favicon.ico" type="image/x-icon" />
  <script src='https://code.jquery.com/jquery-2.1.3.min.js' type='text/javascript'></script>
  <script>
  // http://stackoverflow.com/a/3855394/1475891
  (function($) {
      $.QueryString = (function(a) {
          if (a == "") return {};
          var b = {};
          for (var i = 0; i < a.length; ++i)
          {
              var p=a[i].split('=');
              if (p.length != 2) continue;
              b[p[0]] = decodeURIComponent(p[1].replace(/\+/g, " "));
          }
          return b;
      })(window.location.search.substr(1).split('&'))
  })(jQuery);
  </script>
</head>
<body>
<%= render 'layouts/navigation' %>
<div class="main-container navbar-spacing">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
    <head>
    </head>
    <body>
        <%= yield %>
    </body>
</html>